name: Build and Push to ECR

on:
  push:
    branches:
      - 6-setup-cicd-in-github-actions

env:
  AWS_REGION

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          architecture: x64

      - name: Build with Maven
        run: mvn clean package spring-boot:build-image -Pbuild-image -pl=aws-mp-message-saver

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com

      - name: Push Docker image
        run: docker push ${{ steps.login-ecr.outputs.registry }}/aws-mp-message-saver:latest